version: '3.8'

services:
  # PostgreSQLデータベース
  postgres:
    image: postgres:15-alpine
    container_name: inquiry-postgres
    environment:
      POSTGRES_DB: inquiry_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - inquiry-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: inquiry-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - inquiry-network

  # アプリケーション
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inquiry-app
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: inquiry_management
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - inquiry-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  inquiry-network:
    driver: bridge