// エラーコード定数
export const ERROR_CODES = {
    // 認証・認可エラー
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    INVALID_TOKEN: 'INVALID_TOKEN',

    // バリデーションエラー
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INVALID_INPUT: 'INVALID_INPUT',
    REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',
    INVALID_FORMAT: 'INVALID_FORMAT',

    // リソースエラー
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
    RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',

    // データベースエラー
    DATABASE_ERROR: 'DATABASE_ERROR',
    CONNECTION_ERROR: 'CONNECTION_ERROR',
    TRANSACTION_ERROR: 'TRANSACTION_ERROR',

    // 外部サービスエラー
    EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
    OPENAI_API_ERROR: 'OPENAI_API_ERROR',
    VECTOR_SEARCH_ERROR: 'VECTOR_SEARCH_ERROR',

    // ファイル関連エラー
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',
    INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
    FILE_UPLOAD_ERROR: 'FILE_UPLOAD_ERROR',
    VIRUS_DETECTED: 'VIRUS_DETECTED',

    // レート制限エラー
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

    // システムエラー
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    TIMEOUT_ERROR: 'TIMEOUT_ERROR',
} as const;

// エラーメッセージ
export const ERROR_MESSAGES = {
    [ERROR_CODES.UNAUTHORIZED]: '認証が必要です',
    [ERROR_CODES.FORBIDDEN]: 'この操作を実行する権限がありません',
    [ERROR_CODES.INVALID_CREDENTIALS]: 'ユーザー名またはパスワードが正しくありません',
    [ERROR_CODES.TOKEN_EXPIRED]: 'トークンの有効期限が切れています',
    [ERROR_CODES.INVALID_TOKEN]: '無効なトークンです',

    [ERROR_CODES.VALIDATION_ERROR]: '入力データに不備があります',
    [ERROR_CODES.INVALID_INPUT]: '無効な入力値です',
    [ERROR_CODES.REQUIRED_FIELD_MISSING]: '必須項目が入力されていません',
    [ERROR_CODES.INVALID_FORMAT]: '入力形式が正しくありません',

    [ERROR_CODES.RESOURCE_NOT_FOUND]: '指定されたリソースが見つかりません',
    [ERROR_CODES.RESOURCE_ALREADY_EXISTS]: '指定されたリソースは既に存在します',
    [ERROR_CODES.RESOURCE_CONFLICT]: 'リソースの競合が発生しました',

    [ERROR_CODES.DATABASE_ERROR]: 'データベースエラーが発生しました',
    [ERROR_CODES.CONNECTION_ERROR]: '接続エラーが発生しました',
    [ERROR_CODES.TRANSACTION_ERROR]: 'トランザクションエラーが発生しました',

    [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: '外部サービスでエラーが発生しました',
    [ERROR_CODES.OPENAI_API_ERROR]: 'OpenAI APIでエラーが発生しました',
    [ERROR_CODES.VECTOR_SEARCH_ERROR]: 'ベクトル検索でエラーが発生しました',

    [ERROR_CODES.FILE_TOO_LARGE]: 'ファイルサイズが上限を超えています',
    [ERROR_CODES.INVALID_FILE_TYPE]: '許可されていないファイル形式です',
    [ERROR_CODES.FILE_UPLOAD_ERROR]: 'ファイルのアップロードに失敗しました',
    [ERROR_CODES.VIRUS_DETECTED]: 'ウイルスが検出されました',

    [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 'レート制限を超過しました。しばらく時間をおいてから再試行してください',

    [ERROR_CODES.INTERNAL_SERVER_ERROR]: '内部サーバーエラーが発生しました',
    [ERROR_CODES.SERVICE_UNAVAILABLE]: 'サービスが利用できません',
    [ERROR_CODES.TIMEOUT_ERROR]: 'タイムアウトが発生しました',
} as const;